/* DO NOT EDIT: this file was automatically generated by airtable-ts-codegen */
/* eslint-disable */
import type { Item, Table } from "airtable-ts";

export interface ProjectDock extends Item {
  id: string;
  projectHackatimeId: string;
  user: string[];
  repoLink: string;
  projectHoursReadable: string;
  projectSeconds: number;
  invalid: boolean;
  status: string;
}

export const ProjectDockTable: Table<ProjectDock> = {
  name: "Project Dock",
  baseId: "appUpK8vBRXvkdFai",
  tableId: "tblY3Tp99L3XKDokW",
  mappings: {
    projectHackatimeId: "fldaw8gMBtCkbVrcK",
    user: "fldslTivF3vTEmBDA",
    repoLink: "fldwHQYbLLp8mWCN3",
    projectHoursReadable: "fldo9xlH5TKHxKiAm",
    projectSeconds: "fld3MGx10u5eRxrhr",
    invalid: "fldqwrgPALiSfT5Q5",
    status: "fld7Q7JEWH0OxlYT9",
  },
  schema: {
    projectHackatimeId: "string",
    user: "string[]",
    repoLink: "string",
    projectHoursReadable: "string",
    projectSeconds: "number",
    invalid: "boolean",
    status: "string",
  },
};

export interface User extends Item {
  id: string;
  name: string;
  slackID: string;
  hackatimeUserid: string;
  fudgeType: string;
  allergies: string;
  comments: string;
  status: string;
  projects: string[];
  totalProjectSeconds: number | null;
}

export const usersTable: Table<User> = {
  name: "Users",
  baseId: "appUpK8vBRXvkdFai",
  tableId: "tblPAOIZEraEMrJrw",
  mappings: {
    name: "fldT59BZSxPZp9f8i",
    slackID: "fld6PZfbtJSVr8bxo",
    hackatimeUserid: "fld7ezK41FEOU8fws",
    fudgeType: "fldmxIjTSE9mbXCUZ",
    allergies: "fldg5yWoJ06Fndno0",
    comments: "fld5f4yQjicZKT9EV",
    status: "fldw8KciwAY2dYqrw",
    projects: "fldmGbHroxTp4On8H",
    totalProjectSeconds: "fld6EtHCzLRSVVlyR",
  },
  schema: {
    name: "string",
    slackID: "string",
    hackatimeUserid: "string",
    fudgeType: "string",
    allergies: "string",
    comments: "string",
    status: "string",
    projects: "string[]",
    totalProjectSeconds: "number | null",
  },
};
