/* DO NOT EDIT: this file was automatically generated by airtable-ts-codegen */
/* eslint-disable */
import type { Item, Table } from "airtable-ts";

export interface ProjectDock extends Item {
  id: string;
  projectHackatimeId: string;
  user: string[];
  repoLink: string;
  projectHoursReadable: string;
  projectSeconds: number;
  invalid: boolean;
  status: string;
  repo: string[];
}

export const ProjectDockTable: Table<ProjectDock> = {
  name: "Project Dock",
  baseId: "appUpK8vBRXvkdFai",
  tableId: "tblY3Tp99L3XKDokW",
  mappings: {
    projectHackatimeId: "fldaw8gMBtCkbVrcK",
    user: "fldslTivF3vTEmBDA",
    repoLink: "fldwHQYbLLp8mWCN3",
    projectHoursReadable: "fldo9xlH5TKHxKiAm",
    projectSeconds: "fld3MGx10u5eRxrhr",
    invalid: "fldqwrgPALiSfT5Q5",
    status: "fld7Q7JEWH0OxlYT9",
    repo: "fldm7tt49JBDi33lN",
  },
  schema: {
    projectHackatimeId: "string",
    user: "string[]",
    repoLink: "string",
    projectHoursReadable: "string",
    projectSeconds: "number",
    invalid: "boolean",
    status: "string",
    repo: "string[]",
  },
};

export interface User extends Item {
  id: string;
  name: string;
  slackID: string;
  hackatimeUserid: string;
  fudgeType: string;
  allergies: string;
  comments: string;
  address: string;
  projects: string[];
  totalProjectSeconds: number | null;
  prize: string | null;
  prizeStatus: string;
}

export const usersTable: Table<User> = {
  name: "Users",
  baseId: "appUpK8vBRXvkdFai",
  tableId: "tblPAOIZEraEMrJrw",
  mappings: {
    name: "fldT59BZSxPZp9f8i",
    slackID: "fld6PZfbtJSVr8bxo",
    hackatimeUserid: "fld7ezK41FEOU8fws",
    fudgeType: "fldmxIjTSE9mbXCUZ",
    allergies: "fldg5yWoJ06Fndno0",
    comments: "fld5f4yQjicZKT9EV",
    address: "fldGyWzQ5edwXVbBy",
    projects: "fldmGbHroxTp4On8H",
    totalProjectSeconds: "fld6EtHCzLRSVVlyR",
    prize: "fldnxpLSQZGBYe2tb",
    prizeStatus: "flddKDW75WeBO64ym",
  },
  schema: {
    name: "string",
    slackID: "string",
    hackatimeUserid: "string",
    fudgeType: "string",
    allergies: "string",
    comments: "string",
    address: "string",
    projects: "string[]",
    totalProjectSeconds: "number | null",
    prize: "string | null",
    prizeStatus: "string",
  },
};

export interface FilloutForm extends Item {
  id: string;
  name: string;
  liveLink: string;
  codeLink: string;
  hours: number;
  // Unsupported field Image / Video of type multipleAttachments
  firstName: string;
  lastName: string;
  addressLine1: string;
  addressCity: string;
  addressState: string;
  addressZip: string;
  addressCountry: string;
  rSVPForShowTell: boolean;
  slackUsername: string;
  fullAddress: string;
}

export const FilloutFormTable: Table<FilloutForm> = {
  name: "Fillout form",
  baseId: "appUpK8vBRXvkdFai",
  tableId: "tblb3uTVW3R6cYf1j",
  mappings: {
    name: "fldMdty5Zq2ing3xN",
    liveLink: "fldeUVQqUJhuB7wuE",
    codeLink: "fldJXS0UJ527CYohu",
    hours: "fldfzZm6b3UzpFKDK",
    // Unsupported field Image / Video: fldjcaQQ0hr7QI7Cm
    firstName: "fldicUXjiDFQJw684",
    lastName: "fldh6L6UqTBLYJRLz",
    addressLine1: "fldRX16GLAVekOV4Q",
    addressCity: "fldlOKIsHyfEVyI9L",
    addressState: "fldvMEteKcnlJ7Tg6",
    addressZip: "fldhDT6dZm9rnhJmF",
    addressCountry: "fldaiObZAvlbwG40e",
    rSVPForShowTell: "fldKqFJCDjjnnOTnP",
    slackUsername: "fldbQ5OuZS0hB7ufX",
    fullAddress: "fld8F0O8y6ffB1Pws",
  },
  schema: {
    name: "string",
    liveLink: "string",
    codeLink: "string",
    hours: "number",
    firstName: "string",
    lastName: "string",
    addressLine1: "string",
    addressCity: "string",
    addressState: "string",
    addressZip: "string",
    addressCountry: "string",
    rSVPForShowTell: "boolean",
    slackUsername: "string",
    fullAddress: "string",
  },
};

export interface Repo extends Item {
  id: string;
  name: string;
  link: string;
  hackatimeProjects: string[];
  totalValidSeconds: number | null;
  description: string;
  liveUrl: string;
  demoLink: string;
  projetStatus: string;
}

export const reposTable: Table<Repo> = {
  name: "Repos",
  baseId: "appUpK8vBRXvkdFai",
  tableId: "tbl7D4Ccj2k2hN0lF",
  mappings: {
    name: "fldrRbzP5oT0bZh6u",
    link: "flditV26u6dMa86G0",
    hackatimeProjects: "fldMjHtOJw4UMD65z",
    totalValidSeconds: "fldjchWSacccF1qXC",
    description: "fldcAeA9rF2WXQJYu",
    liveUrl: "fldBijJLGMKTdYcfP",
    demoLink: "fldKLpk6vquiqwQBh",
    projetStatus: "fldVzYNUZiFjIgCRP",
  },
  schema: {
    name: "string",
    link: "string",
    hackatimeProjects: "string[]",
    totalValidSeconds: "number | null",
    description: "string",
    liveUrl: "string",
    demoLink: "string",
    projetStatus: "string",
  },
};
